# Generated by Django 3.1.3 on 2020-12-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201202_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
    ]
