# Generated by Django 3.1.3 on 2020-12-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='url',
        ),
    ]
